import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter_Tight } from 'next/font/google';
import './globals.css';

import { Toaster } from 'sonner';
import QueryProvider from '../components/providers/QueryProviders';
import { CartProvider } from '../context/cart-context';

// 🧩 Font setup
const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const interTight = Inter_Tight({
    variable: '--font-inter-tight',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

// 🪪 Metadata global
export const metadata: Metadata = {
    title: {
        default: 'Havtu Merce',
        template: '%s | Havtu Merce',
    },
    description: 'Generated by Havtu Merce',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${interTight.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
            >
                <QueryProvider>
                    <CartProvider>{children}</CartProvider>
                    <Toaster position="top-right" richColors closeButton />
                </QueryProvider>
            </body>
        </html>
    );
}
